apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: twenty-for-one
  annotations:
    kubernetes.io/ingress.global-static-ip-name: twenty-for-one-ip
    networking.gke.io/managed-certificates: twentyforone-ssl
  labels:
    app: twenty-for-one
spec:
  backend:
    serviceName: twenty-for-one
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: twenty-for-one
spec:
  type: NodePort
  selector:
    app: twenty-for-one
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: twentyforone-ssl
spec:
  domains:
    - twentyforone.com